Build and Deploy MkDocs #18
All jobs
Run details
Re-run triggered now
@jackylawckjackylawck
⁠
 91bf29d
main
Status
Failure
Total duration
6s
Artifacts
–


Annotations
1 error
deploy
Unable to resolve action `actions/setup-python@f67e2a48167775264ee5d6857361ad34726e7990`, unable to find version `f67e2a48167775264ee5d6857361ad34726e7990`
